name: CBOMkit Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cbom-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw -B clean package -DskipTests

      - name: Create CBOM
        uses: cbomkit/cbomkit-action@v2.2.0
        id: cbom
        env:
          CBOMKIT_LANGUAGES: java

      - name: Upload CBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: CBOM
          path: ${{ steps.cbom.outputs.pattern }}
          if-no-files-found: warn